# Redis 线程池设置
spring:
  redis: # redis basic config
    database: 0 # redis数据库索引 Default：0
    host: 127.0.0.1 # redis服务器地址
    port: 6379 # redis port. Default:6379
    password: # Redis服务器连接密码（默认为空）
    timeout: 2000 # 连接超时时间（默认2000毫秒）
    jedis: #Redis线程池设置
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
